name: Update Columns
on:
  schedule:
    - cron: '40 */2 * * *' # Every 2 hours at :40
  workflow_dispatch:

jobs:
  download:
    name: Update Columns
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Retrieve cache
        id: exd-cache
        uses: actions/cache@v4
        with:
          path: data
          key: exd-latest
      
      - name: Download Latest Game Data
        id: downloader
        uses: WorkingRobot/ffxiv-downloader@v2
        with:
          output-path: data
          regex: '^sqpack\/ffxiv\/0a0000\..+$'
    
      - name: Download EXDTools
        uses: robinraju/release-downloader@v1
        with:
          repository: WorkingRobot/EXDTools
          tag: '1.0.0'
          fileName: 'EXDTooler'
      
      - name: Chmod Executable
        run: chmod +x EXDTooler

      - name: Run Column Exporter
        run: ./EXDTooler export-columns -g data/sqpack -o columns/${{steps.downloader.outputs.version}}.yml
      
      - name: Commit Files
        continue-on-error: true
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add -A
          git commit -m "Add column data for ${{steps.downloader.outputs.version}}" --author="${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"

      - name: Push Changes
        continue-on-error: true
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          branch: main
