name: Update Versions
on:
  schedule:
    - cron: '40 */2 * * *' # Every 2 hours at :40
  workflow_dispatch:

jobs:
  update:
    name: Update Versions
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: latest
          fetch-depth: 0
          persist-credentials: false

      - name: Download EXDTools
        uses: robinraju/release-downloader@v1
        with:
          repository: WorkingRobot/EXDTools
          tag: '2.0.0'
          fileName: 'EXDTooler'
      
      - name: Chmod Executable
        run: chmod +x EXDTooler

      - name: Retrieve cache
        id: exd-cache
        uses: actions/cache@v4
        with:
          path: data
          key: exd-latest
      
      - name: Download Latest Game Data
        id: downloader
        uses: WorkingRobot/ffxiv-downloader@v2
        with:
          output-path: data
          regex: '^sqpack\/ffxiv\/0a0000\..+$'
      
      - name: Create Branch
        id: create-branch
        continue-on-error: true
        run: git branch ver/${{steps.downloader.outputs.version}}
      
      - name: Create .github Folder
        if: steps.create-branch.outcome == 'success'
        run: mkdir -p .github

      - name: Run Column Exporter
        if: steps.create-branch.outcome == 'success'
        run: ./EXDTooler export-columns -g data/sqpack -o .github/columns.yml
      
      - name: Commit Files
        if: steps.create-branch.outcome == 'success'
        id: commit
        continue-on-error: true
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .github
          git commit -m "Add column data for ${{steps.downloader.outputs.version}}" --author="${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"

      - name: Push Changes
        if: steps.commit.outcome == 'success'
        run: |
          git checkout ver/${{steps.downloader.outputs.version}}
          git reset --hard latest
          git push origin --all
      
      - name: Add submodule to main
        if: steps.commit.outcome == 'success'
        run: |
          git checkout main
          git submodule add -b ver/${{steps.downloader.outputs.version}} -- https://github.com/WorkingRobot/EXDSchema.git schemas/${{steps.downloader.outputs.version}}
          git add -A
          git commit -m "Add version ${{steps.downloader.outputs.version}}" --author="${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"
      
      - name: Push Submodule
        if: steps.commit.outcome == 'success'
        run: git push origin main

